version: "3.7"
services:
  db:
    image: postgres
    container_name: library_db
    ports:
        - "5432:5432"
    env_file:
        - .development
  web:
    build: .
    image: library
    container_name: library_web
    depends_on:
        - db
    volumes:
        - .:/library
    ports:
        - "8000:8000"
    env_file:
        - .development

